[package]
name = "kernel"
version = "0.1.0"
authors = ["StackDoubleFlow <ojaslandge@gmail.com>"]
edition = "2018"

[dependencies]
bootloader = "0.8.3"
volatile = "0.2.6"
spin = "0.5.2"
x86_64 = "0.7.7"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"